#!/bin/bash
#
# Perform build, run, clean, and deploy tasks(create jar). 

make_sources () {
    # find all the files but exclude emacs backup files
    find . ! -name "*#*" -name "*.java" > files.txt
}

build () {
    rm -rf dist/
    mkdir dist
    make_sources
    javac -classpath . @files.txt -d ./dist
    rm files.txt
}

run () {
    build
    java -classpath ./dist ZombieHouse
}

clean () {
    rm -rf dist/
    rm Manifest.txt
}

gen_manifest () {
    rm Manifest.txt
    touch Manifest.txt
    echo "Manifest-Version: 1.0" >> Manifest.txt
    echo "Class-Path: ./dist/" >> Manifest.txt
    echo "Main-Class: ZombieHouse" >> Manifest.txt
    echo "Created-By: Javier-Alex-Erin (CS351 Project 1)" >> Manifest.txt
}

build_jar () {
    build
    gen_manifest
    jar cvfm ZombieHouseGame.jar Manifest.txt dist/*.class
}

if [ "$1" == "build" ]
then
    build
elif [ "$1" == "run" ]
then
    run
elif [ "$1" == "clean" ]
then
    clean
elif [ "$1" == "deploy" ]
then
    build_jar
    # mkdir zombie-house-game
    # mv ZombieHouseGame.jar zombie-house-game/
    # cp -rf resources zombie-house-game/
else
    echo "Command not found"
fi


