/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'javierc' at '9/8/15 11:15 AM' with Gradle 2.3
 *
 * @author javierc, @date 9/8/15 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
